services:
  - type: web
    name: intraeats-hr-system
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_KEY
        value: base64:vy3FjUlWgMnNrqcQI3tN0EtnCcdtaf7bpBn9F0sfG1M=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_TIMEZONE
        value: Asia/Kolkata
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stderr
