<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\WithMultipleSheets;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use App\Models\Attendance;
use App\Models\Employee;
use App\Models\Project;

class AttendanceReportExport implements WithMultipleSheets
{
    protected $attendances;
    protected $summaryData;

    public function __construct($attendances, array $summaryData = [])
    {
        $this->attendances = $attendances;
        $this->summaryData = $summaryData;
    }

    public function sheets(): array
    {
        return [
            new AttendanceRecordsSheet($this->attendances),
            new AttendanceSummarySheet($this->summaryData),
            new EmployeesSheet(),
            new ProjectsSheet(),
        ];
    }
}

class AttendanceRecordsSheet implements FromCollection, WithHeadings, WithTitle, ShouldAutoSize
{
    protected $attendances;

    public function __construct($attendances)
    {
        $this->attendances = $attendances;
    }

    public function collection()
    {
        return $this->attendances->map(function ($a) {
            return [
                $a->date->format('Y-m-d'),
                $a->employee->employee_id ?? 'N/A',
                $a->employee->employee_code ?? 'N/A',
                $a->employee->full_name ?? 'N/A',
                $a->employee->department ?? 'N/A',
                $a->employee->role ?? 'N/A',
                $a->check_in_time,
                $a->check_out_time ?? '-',
                $a->working_hours_formatted,
                $a->status,
                $a->work_category,
                $a->task_description ?? '-',
                $a->remarks ?? '-',
            ];
        });
    }

    public function headings(): array
    {
        return [
            'Date',
            'Employee ID',
            'Employee Code',
            'Employee Name',
            'Department',
            'Role',
            'Check-in',
            'Check-out',
            'Working Hours',
            'Status',
            'Work Category',
            'Task Description',
            'Remarks',
        ];
    }

    public function title(): string
    {
        return 'Attendance Records';
    }
}

class AttendanceSummarySheet implements FromCollection, WithHeadings, WithTitle, ShouldAutoSize
{
    protected $summary;

    public function __construct(array $summary)
    {
        $this->summary = $summary;
    }

    public function collection()
    {
        return collect([
            ['Metric', 'Value'],
            ['Report Period', $this->summary['period'] ?? 'All Time'],
            ['Total Attendance Records', $this->summary['total'] ?? 0],
            ['Present Records', $this->summary['present'] ?? 0],
            ['Late Records', $this->summary['late'] ?? 0],
            ['Absent Records', $this->summary['absent'] ?? 0],
            ['On Leave Records', $this->summary['leave'] ?? 0],
            ['Attendance Rate %', ($this->summary['rate'] ?? 0) . '%'],
            ['Generated Date', now()->format('Y-m-d H:i:s')],
            ['Generated By', $this->summary['generated_by'] ?? 'IntraEats HR Admin'],
        ]);
    }

    public function headings(): array
    {
        return ['IntraEats HR Analytics', 'Executive Summary'];
    }

    public function title(): string
    {
        return 'Summary';
    }
}

class EmployeesSheet implements FromCollection, WithHeadings, WithTitle, ShouldAutoSize
{
    public function collection()
    {
        return Employee::all()->map(function ($e) {
            return [
                $e->employee_id,
                $e->employee_code,
                $e->full_name,
                $e->email ?? '-',
                $e->mobile ?? '-',
                $e->department,
                $e->designation,
                $e->role,
                $e->employment_type,
                $e->joining_date->format('Y-m-d'),
                $e->status,
                $e->assigned_project ?? '-',
            ];
        });
    }

    public function headings(): array
    {
        return [
            'Employee ID',
            'Employee Code',
            'Full Name',
            'Email',
            'Mobile',
            'Department',
            'Designation',
            'Role',
            'Employment Type',
            'Joining Date',
            'Status',
            'Assigned Project',
        ];
    }

    public function title(): string
    {
        return 'Employees';
    }
}

class ProjectsSheet implements FromCollection, WithHeadings, WithTitle, ShouldAutoSize
{
    public function collection()
    {
        return Project::all()->map(function ($p) {
            return [
                $p->project_id,
                $p->name,
                $p->client,
                $p->manager,
                $p->status,
                $p->start_date ? $p->start_date->format('Y-m-d') : '-',
                $p->end_date ? $p->end_date->format('Y-m-d') : '-',
                $p->description ?? '-',
            ];
        });
    }

    public function headings(): array
    {
        return [
            'Project ID',
            'Project Name',
            'Client',
            'Project Manager',
            'Status',
            'Start Date',
            'End Date',
            'Description',
        ];
    }

    public function title(): string
    {
        return 'Projects';
    }
}
