<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>IntraEats — HR Attendance Report</title>
    <style>
        body { font-family: Helvetica, Arial, sans-serif; font-size: 10px; color: #1C1C1E; margin: 0; padding: 15px; }
        .header-table { width: 100%; border-bottom: 2px solid #FF6B1A; padding-bottom: 12px; margin-bottom: 15px; }
        .logo-box { background: #FF6B1A; color: #ffffff; padding: 6px 12px; border-radius: 6px; font-weight: bold; font-size: 14px; display: inline-block; }
        .title { font-size: 18px; font-weight: bold; color: #1C1C1E; margin: 0; }
        .subtitle { font-size: 10px; color: #64748B; margin: 2px 0 0 0; }
        .meta-text { font-size: 9px; color: #475569; text-align: right; line-height: 1.4; }
        
        .summary-table { width: 100%; border-collapse: collapse; margin-bottom: 15px; background: #F8FAFC; border: 1px solid #E2E8F0; }
        .summary-table td { padding: 8px 12px; text-align: center; border-right: 1px solid #E2E8F0; }
        .summary-table td:last-child { border-right: none; }
        .summary-label { font-size: 8px; text-transform: uppercase; color: #64748B; font-weight: bold; margin-bottom: 3px; }
        .summary-val { font-size: 14px; font-weight: bold; color: #0F172A; }
        
        .data-table { width: 100%; border-collapse: collapse; margin-top: 5px; }
        .data-table th { background: #1E293B; color: #ffffff; text-align: left; padding: 6px 8px; font-size: 9px; text-transform: uppercase; font-weight: bold; }
        .data-table td { padding: 5px 8px; border-bottom: 1px solid #E2E8F0; font-size: 9px; }
        .data-table tr:nth-child(even) { background-color: #F8FAFC; }
        
        .badge { padding: 2px 6px; border-radius: 4px; font-weight: bold; font-size: 8px; text-transform: uppercase; display: inline-block; }
        .badge-present { background: #ECFDF5; color: #059669; }
        .badge-late { background: #FFFBEB; color: #D97706; }
        .badge-absent { background: #FEF2F2; color: #DC2626; }
        .badge-leave { background: #EFF6FF; color: #2563EB; }
        
        .footer { position: fixed; bottom: 10px; left: 15px; right: 15px; border-top: 1px solid #E2E8F0; padding-top: 8px; font-size: 8px; color: #94A3B8; text-align: center; }
    </style>
</head>
<body>
    <table class="header-table">
        <tr>
            <td style="width: 60%;">
                <div class="logo-box">IntraEats</div>
                <h1 class="title" style="margin-top: 6px;">IntraEats &amp; Talisha Software — HR Attendance Report</h1>
                <p class="subtitle">Confidential Workforce Operations &bull; HR Contact: hr@intraeats.com &bull; talishasoftware.tech</p>
            </td>
            <td style="width: 40%;" class="meta-text">
                <strong>Reporting Period:</strong> {{ $summary['period'] }}<br>
                <strong>Generated Date:</strong> {{ now()->format('d M Y, h:i A') }}<br>
                <strong>Generated By:</strong> {{ $summary['generated_by'] }}<br>
                <strong>Total Records:</strong> {{ $summary['total'] }}
            </td>
        </tr>
    </table>

    <table class="summary-table">
        <tr>
            <td>
                <div class="summary-label">Total Records</div>
                <div class="summary-val">{{ $summary['total'] }}</div>
            </td>
            <td>
                <div class="summary-label" style="color: #059669;">Present</div>
                <div class="summary-val" style="color: #059669;">{{ $summary['present'] }}</div>
            </td>
            <td>
                <div class="summary-label" style="color: #D97706;">Late</div>
                <div class="summary-val" style="color: #D97706;">{{ $summary['late'] }}</div>
            </td>
            <td>
                <div class="summary-label" style="color: #DC2626;">Absent</div>
                <div class="summary-val" style="color: #DC2626;">{{ $summary['absent'] }}</div>
            </td>
            <td>
                <div class="summary-label" style="color: #2563EB;">On Leave</div>
                <div class="summary-val" style="color: #2563EB;">{{ $summary['leave'] }}</div>
            </td>
            <td>
                <div class="summary-label">Attendance Rate</div>
                <div class="summary-val">{{ $summary['rate'] }}%</div>
            </td>
            <td>
                <div class="summary-label">Total Logged Hours</div>
                <div class="summary-val">{{ $summary['totalHours'] }} hrs</div>
            </td>
        </tr>
    </table>

    <table class="data-table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Code</th>
                <th>Employee Name</th>
                <th>Department</th>
                <th>Role</th>
                <th>Check-in</th>
                <th>Check-out</th>
                <th>Duration</th>
                <th>Status</th>
                <th>Project / Task</th>
            </tr>
        </thead>
        <tbody>
            @forelse($records as $rec)
            <tr>
                <td><strong>{{ $rec->date->format('Y-m-d') }}</strong></td>
                <td>{{ $rec->employee->employee_code ?? 'N/A' }}</td>
                <td><strong>{{ $rec->employee->full_name ?? 'N/A' }}</strong></td>
                <td>{{ $rec->employee->department ?? '-' }}</td>
                <td>{{ $rec->employee->role ?? '-' }}</td>
                <td>{{ $rec->check_in_time }}</td>
                <td>{{ $rec->check_out_time ?? '-' }}</td>
                <td>{{ $rec->working_hours_formatted }}</td>
                <td>
                    <span class="badge badge-{{ strtolower($rec->status) }}">{{ $rec->status }}</span>
                </td>
                <td>
                    <strong>[{{ $rec->work_category }}]</strong>
                    @if($rec->task_description)
                        <span style="color: #64748B;">{{ Str::limit($rec->task_description, 40) }}</span>
                    @endif
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="10" style="text-align: center; padding: 20px; color: #94A3B8;">No attendance records found for this period.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        &copy; {{ date('Y') }} IntraEats &amp; Talisha Software &bull; Hostinger-Ready Production Report &bull; Page 1 of 1
    </div>
</body>
</html>
